version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            pytest

workflows:
  build-and-deploy:
    jobs:
      - build_and_test
